### ISSUE TITLE
Dockerfile is not working

### ISSUE THREAD

**Issue by inf17101** [eclipse-chariott/Agemo#47]
The Dockerfile is not working when building. There are a view issues listed below in "Current Behavior". 

## Expected Behavior

Dockerfile shall build successfully.

## Current Behavior

The Dockerfile does not built because of the following reasons:

- The rust image refers to local registry: `FROM rust:${RUST_VERSION}-slim-bullseye` must be changed to `FROM docker.io/library/rust:${RUST_VERSION}-slim-bullseye` or other source (same for `FROM debian:bullseye-slim`).
- The rust app `RUN cargo build --features containerize --release ...` is built in "release" mode but the COPY command `COPY --from=build /app/target/debug/*.yaml /sdv/target/debug/` tries to copy something from the `target/debug` folder which is not there when building in release mode.

## Steps to Reproduce

1. Just do the steps of the README for Running with podman

## Context (Environment)

Linux amd64,
Podman

## Logs

After fixing the image pull mentioned above, the error with the COPY command appears:
![image](https://github.com/eclipse-chariott/Agemo/assets/42932060/f22d350b-8a55-4c2a-8a64-bd563efdf40b)

**Comment by devkelley** [comment]
Thank you for the feedback @inf17101! I agree with adding the fully qualified registry and will make that change soon. As for the COPY error you are hitting, it is attempting to copy .yaml configuration files needed to run the service. I am in the process of updating where a user should place those files to be more universal, but currently a user is asked to put the configuration files in 'target/debug'. If you need a workaround, you can try and follow the steps under [Configuration Setup](https://github.com/eclipse-chariott/Agemo#configuration-setup) to create the two yaml config files that need to be copied from the '/target/debug' directory. I will reply back here when I have a PR out for the changes.

**Comment by inf17101** [comment]
> Thank you for the feedback @inf17101! I agree with adding the fully qualified registry and will make that change soon. As for the COPY error you are hitting, it is attempting to copy .yaml configuration files needed to run the service. I am in the process of updating where a user should place those files to be more universal, but currently a user is asked to put the configuration files in 'target/debug'. If you need a workaround, you can try and follow the steps under [Configuration Setup](https://github.com/eclipse-chariott/Agemo#configuration-setup) to create the two yaml config files that need to be copied from the '/target/debug' directory. I will reply back here when I have a PR out for the changes.

@devkelley: Thank you for the reply. And thank you for the changes. That is a really good hint with the config files. We will check the documentation again and check if we missed a part talking about that. If it is not there then a hint in the documentation about that would be great for users.

**Comment by devkelley** [comment]
@inf17101 I just submitted a PR that simplifies the configuration process. There are now default configuration files located in the `.agemo` directory. This should allow for the Dockerfile to be built without any configuration changes. Please ensure you follow the steps outlined in [Running in Podman](https://github.com/eclipse-chariott/Agemo/blob/main/README.md#running-in-podman) as you will need to copy over a podman.env file into the project enlistments root before running the service. Please let us know if you encounter any other issues!
